name: bmi_calculator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  flutter_lints: ^2.0.0
  syncfusion_flutter_gauges: ^23.1.44

flutter:

  uses-material-design: true